name: test tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo -e "echo hello" > testbin
          chmod +x testbin

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}

      - run: echo ${{ steps.vars.outputs.tag }}

      - uses: ./
        with:
          package: testbin
          maintainer: jiro4989
          version: ${{ steps.vars.outputs.tag }}
          arch: 'x86_64'
      - run: sudo dpkg -i *.deb
      - run: which testbin
      - run: testbin
